[tool.ruff]
line-length = 88
src = ["weenat_test_api"]  # your source folder
include = ["*.py"]
exclude = ["migrations", "__pycache__", "venv", ".venv", "env", ".env", ".git"]

[tool.ruff.lint]
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "B",  # bugbear: common bugs & anti-patterns
  "I",  # isort-style import sorting
]
ignore = [
  "E501",  # line length handled by formatter
  "E203"   # spacing around colons (Black compatibility, if ever used)
]
preview = true  # enable latest rules

[tool.ruff.lint.isort]
force-sort-within-sections = true  # strictly sort within each import section
combine-as-imports = true  # combine imports that use 'as'
known-first-party = ["weenat_test_api"]  # your local modules

[tool.ruff.format]
quote-style = "double"
docstring-code-format = true
line-ending = "lf"


[tool.pyright]
typeCheckingMode = "standard"
include = ["weenat_test_api"]
exclude = ["**/migrations", "**/__pycache__"]
reportMissingTypeStubs = false
reportUnknownVariableType = false
reportAssignmentType = "none"
reportIncompatibleVariableOverride = "none"


# [tool.mypy]
# plugins = [
#   "mypy_django_plugin.main",
#   "mypy_drf_plugin.main"
# ]
# strict = false
# disallow_untyped_defs = true
# warn_unused_ignores = true
# check_untyped_defs = true
# show_error_codes = true
# explicit_package_bases = true
# no_implicit_optional = true

# [tool.mypy.plugins]
# "django-stubs" = { django_settings_module = "weenat_test_api.settings" }