# Generated by Django 5.2.1 on 2025-05-28 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datalogger',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lat', models.FloatField(help_text='Latitude in float representation.')),
                ('lng', models.FloatField(help_text='Latitude in float representation.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(choices=[('temp', 'Temperature'), ('rain', 'Rain'), ('hum', 'Humidity')], max_length=20)),
                ('at', models.DateTimeField(help_text='Timestamp when the metric is recorded (ISO-8601 format).')),
                ('value', models.FloatField()),
                ('datalogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datalogger')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
