# Generated by Django 5.2.1 on 2025-05-28 19:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalogger',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='datalogger',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
