# Generated by Django 5.2.1 on 2025-06-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_datalogger_uuid_remove_measurement_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalogger',
            name='lng',
            field=models.FloatField(help_text='Longitude in float representation.'),
        ),
    ]
